In [5]:
import pandas as pl
from os import getenv
from sqlalchemy import create_engine
import polars.selectors as cs
from great_tables import GT, loc, style
%load_ext dotenv
%dotenv

The dotenv extension is already loaded. To reload it, use:
  %reload_ext dotenv

In [4]:
# Define database connection parameters
username = getenv('DB_USER').lower()
password = getenv('DB_PASSWORD')
host = getenv('DB_HOST')
port = getenv('DB_PORT')
database = getenv('DB_NAME')

# Define the connection string
# Format: dialect+driver://username:password@host:port/database
connection_string = f'postgresql://{username}:{password}@{host}:{port}/{database}'

# Create the engine
engine = create_engine(connection_string)
# Import the data to separate dataframes
df_main = pl.read_sql("SELECT * FROM original_data.super_duper_table_of_doom", engine)

In [8]:
df_main

,land,date,ankuenfte_anzahl,ankuenfte_veraenderung_zum_vorjahreszeitraum_prozent,uebernachtungen_anzahl,uebernachtungen_veraenderung_zum_vorjahreszeitraum_prozent,durchsch_aufenthaltsdauer_tage,mean_air_temp_max,mean_air_temp_mean,mean_air_temp_min,...,std_soil_moist,std_soil_temperature_5cm,std_sunshine_duration,campingplaetze_anzahl,urlaubs_campingplaetze_anzahl,urlaubs_campingplaetze_offen,urlaubs_stellplaetze_anzahl,urlaubs_stellplaetze_offen,change_urlaubs_stellplaetze_offen_vorjahresmonat,anteil_urlaubs_stellplaetze_offen_an_urlaubs_stellplaetze_anzah
0,Baden-WÃ¼rttemberg,2024-03-01,78875.0,105.8,219418.0,132.4,2.8,12.374740,7.372771,2.708467,...,3.03137,1.095861,5.038108,None,None,None,None,None,None,None
1,Bayern,2024-03-01,111365.0,160.6,307709.0,161.7,2.8,12.545220,7.136138,2.099823,...,3.638682,0.8525879,7.238923,None,None,None,None,None,None,None
2,Berlin,2024-03-01,1457.0,90.5,5734.0,117.1,3.9,13.168390,8.178442,3.079458,...,0.115587,0.0794624,7.108747,None,None,None,None,None,None,None
3,Brandenburg,2024-03-01,12123.0,193.5,34061.0,281.4,2.8,12.799730,7.691393,2.461740,...,0.760745,0.3207129,7.685427,None,None,None,None,None,None,None
4,Bremen,2024-03-01,6883.0,108.3,12945.0,89.5,1.9,11.955060,8.040822,4.297468,...,0.397123,0.0613891,0.499358,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4250,Hamburg,2022-11-01,3367.0,33.0,NaN,NaN,NaN,9.443800,6.886927,3.879514,...,0.0,0.0845322,2.308657,7.0,3.0,-25.0,215.0,-12.0,506.0,42.5
4251,Bremen,2022-12-01,3606.0,NaN,7746.0,NaN,2.1,5.064556,2.522151,-0.217405,...,1.407978,0.0707927,1.547215,3.0,3.0,0.0,316.0,0.0,316.0,100.0
4252,Hamburg,2022-12-01,2615.0,NaN,3516.0,NaN,1.3,4.688140,2.289622,-0.396495,...,1.851014,0.0640182,0.657893,7.0,3.0,-25.0,215.0,None,506.0,42.5
4253,Saarland,2022-12-01,720.0,NaN,1359.0,NaN,1.9,5.341605,3.027890,0.616942,...,0.68653,0.2909778,2.960537,32.0,14.0,7.0,1089.0,67.0,2146.0,50.7
4254,Sachsen,2022-12-01,1802.0,NaN,5883.0,NaN,3.3,3.742183,1.443099,-1.209170,...,8.939608,0.1913168,4.207757,108.0,36.0,89.0,2306.0,84.0,6603.0,34.9

In [ ]:
sel_rev = cs.starts_with("revenue")
sel_prof = cs.starts_with("profit")

# yo

coffee_table = (
    GT(coffee_sales)
    .tab_header("Sales of Coffee Equipment")
    .tab_spanner(label="Revenue", columns=sel_rev)
    .tab_spanner(label="Profit", columns=sel_prof)
    .cols_label(
        revenue_dollars="Amount",
        profit_dollars="Amount",
        revenue_pct="Percent",
        profit_pct="Percent",
        monthly_sales="Monthly Sales",
        icon="",
        product="Product",
    )
    .fmt_nanoplot("monthly_sales", plot_type="bar")
    .fmt_image("icon", path="_data/coffee-table-icons/")
    .sub_missing(missing_text="")
)

coffee_table